'use client';

const dashboardCode = `<pre class="bg-denim-900 border border-denim-700 rounded-lg p-4 text-denim-100 text-sm overflow-x-auto"><code><span class="syn-kw">import</span> <span class="syn-punc">{</span> <span class="syn-type">useQuery</span> <span class="syn-punc">}</span> <span class="syn-kw">from</span> <span class="syn-str">"@tanstack/react-query"</span><span class="syn-punc">;</span>
<span class="syn-kw">import</span> <span class="syn-punc">{</span> <span class="syn-type">fetchApi</span> <span class="syn-punc">}</span> <span class="syn-kw">from</span> <span class="syn-str">"../query"</span><span class="syn-punc">;</span>

<span class="syn-kw">export</span> <span class="syn-kw">function</span> <span class="syn-fn">DashboardPage</span><span class="syn-punc">()</span> <span class="syn-punc">{</span>
  <span class="syn-kw">const</span> <span class="syn-punc">{</span> <span class="syn-var">data</span><span class="syn-punc">:</span> <span class="syn-var">customers</span> <span class="syn-punc">}</span> <span class="syn-op">=</span> <span class="syn-fn">useQuery</span><span class="syn-punc">({</span>
    <span class="syn-var">queryKey</span><span class="syn-punc">:</span> <span class="syn-punc">["</span><span class="syn-str">customers</span><span class="syn-punc">"],</span>
    <span class="syn-var">queryFn</span><span class="syn-punc">:</span> <span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">fetchApi</span><span class="syn-punc">(</span><span class="syn-str">"/customers"</span><span class="syn-punc">)</span> <span class="syn-kw">as</span> <span class="syn-type">Promise</span><span class="syn-op">&lt;</span><span class="syn-punc">{</span> <span class="syn-var">id</span><span class="syn-punc">:</span> <span class="syn-type">number</span><span class="syn-punc">;</span> <span class="syn-var">name</span><span class="syn-punc">:</span> <span class="syn-type">string</span> <span class="syn-punc">}</span><span class="syn-op">&gt;</span><span class="syn-punc">[]</span><span class="syn-op">&gt;</span><span class="syn-punc">,</span>
  <span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">;</span>

  <span class="syn-kw">const</span> <span class="syn-punc">{</span> <span class="syn-var">data</span><span class="syn-punc">:</span> <span class="syn-var">invoices</span> <span class="syn-punc">}</span> <span class="syn-op">=</span> <span class="syn-fn">useQuery</span><span class="syn-punc">({</span>
    <span class="syn-var">queryKey</span><span class="syn-punc">:</span> <span class="syn-punc">["</span><span class="syn-str">invoices</span><span class="syn-punc">"],</span>
    <span class="syn-var">queryFn</span><span class="syn-punc">:</span> <span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">fetchApi</span><span class="syn-punc">(</span><span class="syn-str">"/invoices"</span><span class="syn-punc">)</span> <span class="syn-kw">as</span> <span class="syn-type">Promise</span><span class="syn-op">&lt;</span><span class="syn-punc">{</span> <span class="syn-var">id</span><span class="syn-punc">:</span> <span class="syn-type">number</span><span class="syn-punc">;</span> <span class="syn-var">amount</span><span class="syn-punc">:</span> <span class="syn-type">number</span><span class="syn-punc">;</span> <span class="syn-var">status</span><span class="syn-punc">:</span> <span class="syn-type">string</span> <span class="syn-punc">}</span><span class="syn-op">&gt;</span><span class="syn-punc">[]</span><span class="syn-op">&gt;</span><span class="syn-punc">,</span>
  <span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">;</span>

  <span class="syn-kw">const</span> <span class="syn-var">stats</span> <span class="syn-op">=</span> <span class="syn-punc">{</span>
    <span class="syn-var">totalCustomers</span><span class="syn-punc">:</span> <span class="syn-var">customers</span><span class="syn-punc">?.</span><span class="syn-var">length</span> <span class="syn-op">??</span> <span class="syn-num">0</span><span class="syn-punc">,</span>
    <span class="syn-var">totalInvoices</span><span class="syn-punc">:</span> <span class="syn-var">invoices</span><span class="syn-punc">?.</span><span class="syn-var">length</span> <span class="syn-op">??</span> <span class="syn-num">0</span><span class="syn-punc">,</span>
    <span class="syn-var">pendingAmount</span><span class="syn-punc">:</span> <span class="syn-var">invoices</span>
      <span class="syn-punc">?.</span><span class="syn-fn">filter</span><span class="syn-punc">((</span><span class="syn-var">i</span><span class="syn-punc">)</span> <span class="syn-op">=&gt;</span> <span class="syn-var">i</span><span class="syn-punc">.</span><span class="syn-var">status</span> <span class="syn-op">===</span> <span class="syn-str">"pending"</span><span class="syn-punc">)</span>
      <span class="syn-punc">.</span><span class="syn-fn">reduce</span><span class="syn-punc">((</span><span class="syn-var">sum</span><span class="syn-punc">,</span> <span class="syn-var">i</span><span class="syn-punc">)</span> <span class="syn-op">=&gt;</span> <span class="syn-var">sum</span> <span class="syn-op">+</span> <span class="syn-var">i</span><span class="syn-punc">.</span><span class="syn-var">amount</span><span class="syn-punc">,</span> <span class="syn-num">0</span><span class="syn-punc">)</span>
      <span class="syn-punc">.</span><span class="syn-fn">toFixed</span><span class="syn-punc">(</span><span class="syn-num">2</span><span class="syn-punc">)</span> <span class="syn-op">??</span> <span class="syn-str">"0.00"</span><span class="syn-punc">,</span>
  <span class="syn-punc">}</span><span class="syn-punc">;</span>

  <span class="syn-kw">return</span> <span class="syn-punc">(</span>
    <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"p-6"</span><span class="syn-op">&gt;</span>
      <span class="syn-op">&lt;</span><span class="syn-type">h1</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-3xl font-bold text-denim-50 mb-6"</span><span class="syn-op">&gt;</span><span class="syn-str">Dashboard</span><span class="syn-op">&lt;/</span><span class="syn-type">h1</span><span class="syn-op">&gt;</span>
      <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"grid grid-cols-3 gap-4 mb-8"</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"bg-denim-800 p-4 rounded"</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;</span><span class="syn-type">p</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-denim-400 text-sm"</span><span class="syn-op">&gt;</span><span class="syn-str">Customers</span><span class="syn-op">&lt;/</span><span class="syn-type">p</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;</span><span class="syn-type">p</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-3xl font-bold text-denim-50"</span><span class="syn-op">&gt;</span><span class="syn-punc">{</span><span class="syn-var">stats</span><span class="syn-punc">.</span><span class="syn-var">totalCustomers</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">p</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"bg-denim-800 p-4 rounded"</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;</span><span class="syn-type">p</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-denim-400 text-sm"</span><span class="syn-op">&gt;</span><span class="syn-str">Invoices</span><span class="syn-op">&lt;/</span><span class="syn-type">p</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;</span><span class="syn-type">p</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-3xl font-bold text-denim-50"</span><span class="syn-op">&gt;</span><span class="syn-punc">{</span><span class="syn-var">stats</span><span class="syn-punc">.</span><span class="syn-var">totalInvoices</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">p</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"bg-denim-800 p-4 rounded"</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;</span><span class="syn-type">p</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-denim-400 text-sm"</span><span class="syn-op">&gt;</span><span class="syn-str">Pending ($)</span><span class="syn-op">&lt;/</span><span class="syn-type">p</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;</span><span class="syn-type">p</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-3xl font-bold text-wash-400"</span><span class="syn-op">&gt;</span><span class="syn-str">$</span><span class="syn-punc">{</span><span class="syn-var">stats</span><span class="syn-punc">.</span><span class="syn-var">pendingAmount</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">p</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
      <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
    <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
  <span class="syn-punc">)</span><span class="syn-punc">;</span>
<span class="syn-punc">}</span></code></pre>`;

const customersCode = `<pre class="bg-denim-900 border border-denim-700 rounded-lg p-4 text-denim-100 text-sm overflow-x-auto"><code><span class="syn-kw">import</span> <span class="syn-punc">{</span> <span class="syn-type">useState</span> <span class="syn-punc">}</span> <span class="syn-kw">from</span> <span class="syn-str">"react"</span><span class="syn-punc">;</span>
<span class="syn-kw">import</span> <span class="syn-punc">{</span> <span class="syn-type">useQuery</span><span class="syn-punc">,</span> <span class="syn-type">useMutation</span><span class="syn-punc">,</span> <span class="syn-type">useQueryClient</span> <span class="syn-punc">}</span> <span class="syn-kw">from</span> <span class="syn-str">"@tanstack/react-query"</span><span class="syn-punc">;</span>
<span class="syn-kw">import</span> <span class="syn-punc">{</span> <span class="syn-type">fetchApi</span> <span class="syn-punc">}</span> <span class="syn-kw">from</span> <span class="syn-str">"../query"</span><span class="syn-punc">;</span>

<span class="syn-kw">type</span> <span class="syn-type">Customer</span> <span class="syn-op">=</span> <span class="syn-punc">{</span> <span class="syn-var">id</span><span class="syn-punc">:</span> <span class="syn-type">number</span><span class="syn-punc">;</span> <span class="syn-var">name</span><span class="syn-punc">:</span> <span class="syn-type">string</span><span class="syn-punc">;</span> <span class="syn-var">email</span><span class="syn-punc">:</span> <span class="syn-type">string</span><span class="syn-punc">;</span> <span class="syn-var">phone</span><span class="syn-punc">:</span> <span class="syn-type">string</span> <span class="syn-punc">}</span><span class="syn-punc">;</span>

<span class="syn-kw">export</span> <span class="syn-kw">function</span> <span class="syn-fn">CustomersPage</span><span class="syn-punc">()</span> <span class="syn-punc">{</span>
  <span class="syn-kw">const</span> <span class="syn-var">queryClient</span> <span class="syn-op">=</span> <span class="syn-fn">useQueryClient</span><span class="syn-punc">()</span><span class="syn-punc">;</span>
  <span class="syn-kw">const</span> <span class="syn-punc">[</span><span class="syn-var">showModal</span><span class="syn-punc">,</span> <span class="syn-fn">setShowModal</span><span class="syn-punc">]</span> <span class="syn-op">=</span> <span class="syn-fn">useState</span><span class="syn-punc">(</span><span class="syn-kw">false</span><span class="syn-punc">)</span><span class="syn-punc">;</span>
  <span class="syn-kw">const</span> <span class="syn-punc">[</span><span class="syn-var">editCustomer</span><span class="syn-punc">,</span> <span class="syn-fn">setEditCustomer</span><span class="syn-punc">]</span> <span class="syn-op">=</span> <span class="syn-fn">useState</span><span class="syn-punc">&lt;</span><span class="syn-type">Customer</span> <span class="syn-op">|</span> <span class="syn-kw">null</span><span class="syn-op">&gt;</span><span class="syn-punc">(</span><span class="syn-kw">null</span><span class="syn-punc">)</span><span class="syn-punc">;</span>
  <span class="syn-kw">const</span> <span class="syn-punc">[</span><span class="syn-var">form</span><span class="syn-punc">,</span> <span class="syn-fn">setForm</span><span class="syn-punc">]</span> <span class="syn-op">=</span> <span class="syn-fn">useState</span><span class="syn-punc">({</span> <span class="syn-var">name</span><span class="syn-punc">:</span> <span class="syn-str">""</span><span class="syn-punc">,</span> <span class="syn-var">email</span><span class="syn-punc">:</span> <span class="syn-str">""</span><span class="syn-punc">,</span> <span class="syn-var">phone</span><span class="syn-punc">:</span> <span class="syn-str">""</span> <span class="syn-punc">})</span><span class="syn-punc">;</span>

  <span class="syn-kw">const</span> <span class="syn-punc">{</span> <span class="syn-var">data</span><span class="syn-punc">:</span> <span class="syn-var">customers</span> <span class="syn-punc">}</span> <span class="syn-op">=</span> <span class="syn-fn">useQuery</span><span class="syn-punc">({</span>
    <span class="syn-var">queryKey</span><span class="syn-punc">:</span> <span class="syn-punc">["</span><span class="syn-str">customers</span><span class="syn-punc">"],</span>
    <span class="syn-var">queryFn</span><span class="syn-punc">:</span> <span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">fetchApi</span><span class="syn-punc">(</span><span class="syn-str">"/customers"</span><span class="syn-punc">)</span> <span class="syn-kw">as</span> <span class="syn-type">Promise</span><span class="syn-op">&lt;</span><span class="syn-type">Customer</span><span class="syn-punc">[]</span><span class="syn-op">&gt;</span><span class="syn-punc">,</span>
  <span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">;</span>

  <span class="syn-kw">const</span> <span class="syn-var">addMutation</span> <span class="syn-op">=</span> <span class="syn-fn">useMutation</span><span class="syn-punc">({</span>
    <span class="syn-var">mutationFn</span><span class="syn-punc">:</span> <span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">fetchApi</span><span class="syn-punc">(</span><span class="syn-str">"/customers"</span><span class="syn-punc">,</span> <span class="syn-punc">{</span> <span class="syn-var">method</span><span class="syn-punc">:</span> <span class="syn-str">"POST"</span><span class="syn-punc">,</span> <span class="syn-var">body</span><span class="syn-punc">:</span> <span class="syn-fn">JSON</span><span class="syn-punc">.</span><span class="syn-fn">stringify</span><span class="syn-punc">(</span><span class="syn-var">form</span><span class="syn-punc">)</span> <span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">,</span>
    <span class="syn-var">onSuccess</span><span class="syn-punc">:</span> <span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-punc">{</span>
      <span class="syn-fn">setShowModal</span><span class="syn-punc">(</span><span class="syn-kw">false</span><span class="syn-punc">)</span><span class="syn-punc">;</span>
      <span class="syn-fn">setForm</span><span class="syn-punc">({</span> <span class="syn-var">name</span><span class="syn-punc">:</span> <span class="syn-str">""</span><span class="syn-punc">,</span> <span class="syn-var">email</span><span class="syn-punc">:</span> <span class="syn-str">""</span><span class="syn-punc">,</span> <span class="syn-var">phone</span><span class="syn-punc">:</span> <span class="syn-str">""</span> <span class="syn-punc">})</span><span class="syn-punc">;</span>
      <span class="syn-var">queryClient</span><span class="syn-punc">.</span><span class="syn-fn">invalidateQueries</span><span class="syn-punc">({</span> <span class="syn-var">queryKey</span><span class="syn-punc">:</span> <span class="syn-punc">["</span><span class="syn-str">customers</span><span class="syn-punc">"]</span> <span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">;</span>
    <span class="syn-punc">}</span><span class="syn-punc">,</span>
  <span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">;</span>

  <span class="syn-kw">const</span> <span class="syn-var">editMutation</span> <span class="syn-op">=</span> <span class="syn-fn">useMutation</span><span class="syn-punc">({</span>
    <span class="syn-var">mutationFn</span><span class="syn-punc">:</span> <span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">fetchApi</span><span class="syn-punc">(</span><span class="syn-str">"/customers/"</span> <span class="syn-op">+</span> <span class="syn-var">editCustomer</span><span class="syn-punc">?.</span><span class="syn-var">id</span><span class="syn-punc">,</span> <span class="syn-punc">{</span> <span class="syn-var">method</span><span class="syn-punc">:</span> <span class="syn-str">"PUT"</span><span class="syn-punc">,</span> <span class="syn-var">body</span><span class="syn-punc">:</span> <span class="syn-fn">JSON</span><span class="syn-punc">.</span><span class="syn-fn">stringify</span><span class="syn-punc">(</span><span class="syn-var">form</span><span class="syn-punc">)</span> <span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">,</span>
    <span class="syn-var">onSuccess</span><span class="syn-punc">:</span> <span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-punc">{</span>
      <span class="syn-fn">setEditCustomer</span><span class="syn-punc">(</span><span class="syn-kw">null</span><span class="syn-punc">)</span><span class="syn-punc">;</span>
      <span class="syn-var">queryClient</span><span class="syn-punc">.</span><span class="syn-fn">invalidateQueries</span><span class="syn-punc">({</span> <span class="syn-var">queryKey</span><span class="syn-punc">:</span> <span class="syn-punc">["</span><span class="syn-str">customers</span><span class="syn-punc">"]</span> <span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">;</span>
    <span class="syn-punc">}</span><span class="syn-punc">,</span>
  <span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">;</span>

  <span class="syn-kw">const</span> <span class="syn-fn">openEdit</span> <span class="syn-op">=</span> <span class="syn-punc">(</span><span class="syn-var">c</span><span class="syn-punc">:</span> <span class="syn-type">Customer</span><span class="syn-punc">)</span> <span class="syn-op">=&gt;</span> <span class="syn-punc">{</span>
    <span class="syn-fn">setEditCustomer</span><span class="syn-punc">(</span><span class="syn-var">c</span><span class="syn-punc">)</span><span class="syn-punc">;</span>
    <span class="syn-fn">setForm</span><span class="syn-punc">({</span> <span class="syn-var">name</span><span class="syn-punc">:</span> <span class="syn-var">c</span><span class="syn-punc">.</span><span class="syn-var">name</span><span class="syn-punc">,</span> <span class="syn-var">email</span><span class="syn-punc">:</span> <span class="syn-var">c</span><span class="syn-punc">.</span><span class="syn-var">email</span><span class="syn-punc">,</span> <span class="syn-var">phone</span><span class="syn-punc">:</span> <span class="syn-var">c</span><span class="syn-punc">.</span><span class="syn-var">phone</span> <span class="syn-punc">})</span><span class="syn-punc">;</span>
    <span class="syn-fn">setShowModal</span><span class="syn-punc">(</span><span class="syn-kw">true</span><span class="syn-punc">)</span><span class="syn-punc">;</span>
  <span class="syn-punc">}</span><span class="syn-punc">;</span>

  <span class="syn-kw">return</span> <span class="syn-punc">(</span>
    <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"p-6"</span><span class="syn-op">&gt;</span>
      <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"flex justify-between items-center mb-6"</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;</span><span class="syn-type">h1</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-3xl font-bold text-denim-50"</span><span class="syn-op">&gt;</span><span class="syn-str">Customers</span><span class="syn-op">&lt;/</span><span class="syn-type">h1</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;</span><span class="syn-type">button</span> <span class="syn-attr">onClick</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">setShowModal</span><span class="syn-punc">(</span><span class="syn-kw">true</span><span class="syn-punc">)</span><span class="syn-punc">}</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"px-4 py-2 bg-wash-600 text-denim-50 rounded"</span><span class="syn-op">&gt;</span>
          + Add Customer
        <span class="syn-op">&lt;/</span><span class="syn-type">button</span><span class="syn-op">&gt;</span>
      <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>

      <span class="syn-op">&lt;</span><span class="syn-type">table</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"w-full text-denim-50"</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;</span><span class="syn-type">thead</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;</span><span class="syn-type">tr</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-left border-b border-denim-700"</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">th</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"pb-2"</span><span class="syn-op">&gt;</span><span class="syn-str">Name</span><span class="syn-op">&lt;/</span><span class="syn-type">th</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">th</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"pb-2"</span><span class="syn-op">&gt;</span><span class="syn-str">Email</span><span class="syn-op">&lt;/</span><span class="syn-type">th</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">th</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"pb-2"</span><span class="syn-op">&gt;</span><span class="syn-str">Phone</span><span class="syn-op">&lt;/</span><span class="syn-type">th</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">th</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"pb-2"</span><span class="syn-op">&gt;</span><span class="syn-str">Actions</span><span class="syn-op">&lt;/</span><span class="syn-type">th</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;/</span><span class="syn-type">tr</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;/</span><span class="syn-type">thead</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;</span><span class="syn-type">tbody</span><span class="syn-op">&gt;</span>
          <span class="syn-punc">{(</span><span class="syn-var">customers</span> <span class="syn-op">??</span> <span class="syn-punc">[]).</span><span class="syn-fn">map</span><span class="syn-punc">((</span><span class="syn-var">c</span><span class="syn-punc">)</span> <span class="syn-op">=&gt;</span> <span class="syn-punc">(</span>
            <span class="syn-op">&lt;</span><span class="syn-type">tr</span> <span class="syn-attr">key</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-var">c</span><span class="syn-punc">.</span><span class="syn-var">id</span><span class="syn-punc">}</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"border-b border-denim-800"</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">td</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"py-3"</span><span class="syn-op">&gt;</span><span class="syn-punc">{</span><span class="syn-var">c</span><span class="syn-punc">.</span><span class="syn-var">name</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">td</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">td</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"py-3"</span><span class="syn-op">&gt;</span><span class="syn-punc">{</span><span class="syn-var">c</span><span class="syn-punc">.</span><span class="syn-var">email</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">td</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">td</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"py-3"</span><span class="syn-op">&gt;</span><span class="syn-punc">{</span><span class="syn-var">c</span><span class="syn-punc">.</span><span class="syn-var">phone</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">td</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">td</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"py-3"</span><span class="syn-op">&gt;</span>
                <span class="syn-op">&lt;</span><span class="syn-type">button</span> <span class="syn-attr">onClick</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">openEdit</span><span class="syn-punc">(</span><span class="syn-var">c</span><span class="syn-punc">)</span><span class="syn-punc">}</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-wash-400 hover:text-wash-300 mr-3"</span><span class="syn-op">&gt;</span>Edit<span class="syn-op">&lt;/</span><span class="syn-type">button</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;/</span><span class="syn-type">td</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;/</span><span class="syn-type">tr</span><span class="syn-op">&gt;</span>
          <span class="syn-punc">))}</span>
        <span class="syn-op">&lt;/</span><span class="syn-type">tbody</span><span class="syn-op">&gt;</span>
      <span class="syn-op">&lt;/</span><span class="syn-type">table</span><span class="syn-op">&gt;</span>

      <span class="syn-punc">{(</span><span class="syn-var">showModal</span> <span class="syn-op">||</span> <span class="syn-var">editCustomer</span><span class="syn-punc">)</span> <span class="syn-op">&amp;&amp;</span> <span class="syn-punc">(</span>
        <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"fixed inset-0 bg-black/50 flex items-center justify-center"</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"bg-denim-800 p-6 rounded-lg w-96"</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">h2</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-xl font-bold text-denim-50 mb-4"</span><span class="syn-op">&gt;</span>
              <span class="syn-punc">{</span><span class="syn-var">editCustomer</span> <span class="syn-op">?</span> <span class="syn-str">"Edit Customer"</span> <span class="syn-op">:</span> <span class="syn-str">"Add Customer"</span><span class="syn-punc">}</span>
            <span class="syn-op">&lt;/</span><span class="syn-type">h2</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">input</span> <span class="syn-attr">placeholder</span><span class="syn-op">=</span><span class="syn-str">"Name"</span> <span class="syn-attr">value</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-var">form</span><span class="syn-punc">.</span><span class="syn-var">name</span><span class="syn-punc">}</span> <span class="syn-attr">onChange</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-punc">(</span><span class="syn-var">e</span><span class="syn-punc">)</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">setForm</span><span class="syn-punc">({</span><span class="syn-var">f</span><span class="syn-punc">...</span><span class="syn-var">form</span><span class="syn-punc">,</span> <span class="syn-var">name</span><span class="syn-punc">:</span> <span class="syn-var">e</span><span class="syn-punc">.</span><span class="syn-var">target</span><span class="syn-punc">.</span><span class="syn-var">value</span><span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">}</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"w-full p-2 mb-3 bg-denim-700 rounded text-denim-50"</span><span class="syn-op">/&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">input</span> <span class="syn-attr">placeholder</span><span class="syn-op">=</span><span class="syn-str">"Email"</span> <span class="syn-attr">value</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-var">form</span><span class="syn-punc">.</span><span class="syn-var">email</span><span class="syn-punc">}</span> <span class="syn-attr">onChange</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-punc">(</span><span class="syn-var">e</span><span class="syn-punc">)</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">setForm</span><span class="syn-punc">({</span><span class="syn-var">f</span><span class="syn-punc">...</span><span class="syn-var">form</span><span class="syn-punc">,</span> <span class="syn-var">email</span><span class="syn-punc">:</span> <span class="syn-var">e</span><span class="syn-punc">.</span><span class="syn-var">target</span><span class="syn-punc">.</span><span class="syn-var">value</span><span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">}</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"w-full p-2 mb-3 bg-denim-700 rounded text-denim-50"</span><span class="syn-op">/&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">input</span> <span class="syn-attr">placeholder</span><span class="syn-op">=</span><span class="syn-str">"Phone"</span> <span class="syn-attr">value</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-var">form</span><span class="syn-punc">.</span><span class="syn-var">phone</span><span class="syn-punc">}</span> <span class="syn-attr">onChange</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-punc">(</span><span class="syn-var">e</span><span class="syn-punc">)</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">setForm</span><span class="syn-punc">({</span><span class="syn-var">f</span><span class="syn-punc">...</span><span class="syn-var">form</span><span class="syn-punc">,</span> <span class="syn-var">phone</span><span class="syn-punc">:</span> <span class="syn-var">e</span><span class="syn-punc">.</span><span class="syn-var">target</span><span class="syn-punc">.</span><span class="syn-var">value</span><span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">}</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"w-full p-2 mb-4 bg-denim-700 rounded text-denim-50"</span><span class="syn-op">/&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"flex justify-end gap-2"</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">button</span> <span class="syn-attr">onClick</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-punc">{</span> <span class="syn-fn">setShowModal</span><span class="syn-punc">(</span><span class="syn-kw">false</span><span class="syn-punc">)</span><span class="syn-punc">;</span> <span class="syn-fn">setEditCustomer</span><span class="syn-punc">(</span><span class="syn-kw">null</span><span class="syn-punc">)</span><span class="syn-punc">;</span> <span class="syn-punc">}</span><span class="syn-punc">}</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"px-4 py-2 text-denim-400"</span><span class="syn-op">&gt;</span>Cancel<span class="syn-op">&lt;/</span><span class="syn-type">button</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">button</span> <span class="syn-attr">onClick</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-var">editCustomer</span> <span class="syn-op">?</span> <span class="syn-var">editMutation</span><span class="syn-punc">.</span><span class="syn-fn">mutate</span><span class="syn-punc">()</span> <span class="syn-op">:</span> <span class="syn-var">addMutation</span><span class="syn-punc">.</span><span class="syn-fn">mutate</span><span class="syn-punc">()</span><span class="syn-punc">}</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"px-4 py-2 bg-wash-600 text-denim-50 rounded"</span><span class="syn-op">&gt;</span>
                <span class="syn-punc">{</span><span class="syn-var">editCustomer</span> <span class="syn-op">?</span> <span class="syn-str">"Update"</span> <span class="syn-op">:</span> <span class="syn-str">"Add"</span><span class="syn-punc">}</span>
              <span class="syn-op">&lt;/</span><span class="syn-type">button</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
      <span class="syn-punc">)}</span>
    <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
  <span class="syn-punc">)</span><span class="syn-punc">;</span>
<span class="syn-punc">}</span></code></pre>`;

const invoicesCode = `<pre class="bg-denim-900 border border-denim-700 rounded-lg p-4 text-denim-100 text-sm overflow-x-auto"><code><span class="syn-kw">import</span> <span class="syn-punc">{</span> <span class="syn-type">useState</span> <span class="syn-punc">}</span> <span class="syn-kw">from</span> <span class="syn-str">"react"</span><span class="syn-punc">;</span>
<span class="syn-kw">import</span> <span class="syn-punc">{</span> <span class="syn-type">useQuery</span><span class="syn-punc">,</span> <span class="syn-type">useMutation</span><span class="syn-punc">,</span> <span class="syn-type">useQueryClient</span> <span class="syn-punc">}</span> <span class="syn-kw">from</span> <span class="syn-str">"@tanstack/react-query"</span><span class="syn-punc">;</span>
<span class="syn-kw">import</span> <span class="syn-punc">{</span> <span class="syn-type">fetchApi</span> <span class="syn-punc">}</span> <span class="syn-kw">from</span> <span class="syn-str">"../query"</span><span class="syn-punc">;</span>

<span class="syn-kw">type</span> <span class="syn-type">Invoice</span> <span class="syn-op">=</span> <span class="syn-punc">{</span>
  <span class="syn-var">id</span><span class="syn-punc">:</span> <span class="syn-type">number</span><span class="syn-punc">;</span>
  <span class="syn-var">customer_id</span><span class="syn-punc">:</span> <span class="syn-type">number</span><span class="syn-punc">;</span>
  <span class="syn-var">customer_name</span><span class="syn-punc">:</span> <span class="syn-type">string</span><span class="syn-punc">;</span>
  <span class="syn-var">amount</span><span class="syn-punc">:</span> <span class="syn-type">number</span><span class="syn-punc">;</span>
  <span class="syn-var">status</span><span class="syn-punc">:</span> <span class="syn-type">string</span><span class="syn-punc">;</span>
  <span class="syn-var">due_date</span><span class="syn-punc">:</span> <span class="syn-type">string</span><span class="syn-punc">;</span>
  <span class="syn-var">description</span><span class="syn-punc">:</span> <span class="syn-type">string</span><span class="syn-punc">;</span>
<span class="syn-punc">}</span><span class="syn-punc">;</span>

<span class="syn-kw">export</span> <span class="syn-kw">function</span> <span class="syn-fn">InvoicesPage</span><span class="syn-punc">()</span> <span class="syn-punc">{</span>
  <span class="syn-kw">const</span> <span class="syn-var">queryClient</span> <span class="syn-op">=</span> <span class="syn-fn">useQueryClient</span><span class="syn-punc">()</span><span class="syn-punc">;</span>
  <span class="syn-kw">const</span> <span class="syn-punc">[</span><span class="syn-var">viewInvoice</span><span class="syn-punc">,</span> <span class="syn-fn">setViewInvoice</span><span class="syn-punc">]</span> <span class="syn-op">=</span> <span class="syn-fn">useState</span><span class="syn-punc">&lt;</span><span class="syn-type">Invoice</span> <span class="syn-op">|</span> <span class="syn-kw">null</span><span class="syn-op">&gt;</span><span class="syn-punc">(</span><span class="syn-kw">null</span><span class="syn-punc">)</span><span class="syn-punc">;</span>

  <span class="syn-kw">const</span> <span class="syn-punc">{</span> <span class="syn-var">data</span><span class="syn-punc">:</span> <span class="syn-var">invoices</span> <span class="syn-punc">}</span> <span class="syn-op">=</span> <span class="syn-fn">useQuery</span><span class="syn-punc">({</span>
    <span class="syn-var">queryKey</span><span class="syn-punc">:</span> <span class="syn-punc">["</span><span class="syn-str">invoices</span><span class="syn-punc">"],</span>
    <span class="syn-var">queryFn</span><span class="syn-punc">:</span> <span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">fetchApi</span><span class="syn-punc">(</span><span class="syn-str">"/invoices"</span><span class="syn-punc">)</span> <span class="syn-kw">as</span> <span class="syn-type">Promise</span><span class="syn-op">&lt;</span><span class="syn-type">Invoice</span><span class="syn-punc">[]</span><span class="syn-op">&gt;</span><span class="syn-punc">,</span>
  <span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">;</span>

  <span class="syn-kw">const</span> <span class="syn-var">statusMutation</span> <span class="syn-op">=</span> <span class="syn-fn">useMutation</span><span class="syn-punc">({</span>
    <span class="syn-var">mutationFn</span><span class="syn-punc">:</span> <span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">fetchApi</span><span class="syn-punc">(</span><span class="syn-str">"/invoices/"</span> <span class="syn-op">+</span> <span class="syn-var">viewInvoice</span><span class="syn-punc">?.</span><span class="syn-var">id</span><span class="syn-punc">,</span> <span class="syn-punc">{</span> <span class="syn-var">method</span><span class="syn-punc">:</span> <span class="syn-str">"PATCH"</span><span class="syn-punc">,</span> <span class="syn-var">body</span><span class="syn-punc">:</span> <span class="syn-fn">JSON</span><span class="syn-punc">.</span><span class="syn-fn">stringify</span><span class="syn-punc">({</span> <span class="syn-var">status</span><span class="syn-punc">:</span> <span class="syn-str">"paid"</span> <span class="syn-punc">}</span><span class="syn-punc">)</span> <span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">,</span>
    <span class="syn-var">onSuccess</span><span class="syn-punc">:</span> <span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-punc">{</span>
      <span class="syn-fn">setViewInvoice</span><span class="syn-punc">(</span><span class="syn-kw">null</span><span class="syn-punc">)</span><span class="syn-punc">;</span>
      <span class="syn-var">queryClient</span><span class="syn-punc">.</span><span class="syn-fn">invalidateQueries</span><span class="syn-punc">({</span> <span class="syn-var">queryKey</span><span class="syn-punc">:</span> <span class="syn-punc">["</span><span class="syn-str">invoices</span><span class="syn-punc">"]</span> <span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">;</span>
    <span class="syn-punc">}</span><span class="syn-punc">,</span>
  <span class="syn-punc">}</span><span class="syn-punc">)</span><span class="syn-punc">;</span>

  <span class="syn-kw">return</span> <span class="syn-punc">(</span>
    <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"p-6"</span><span class="syn-op">&gt;</span>
      <span class="syn-op">&lt;</span><span class="syn-type">h1</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-3xl font-bold text-denim-50 mb-6"</span><span class="syn-op">&gt;</span><span class="syn-str">Invoices</span><span class="syn-op">&lt;/</span><span class="syn-type">h1</span><span class="syn-op">&gt;</span>

      <span class="syn-op">&lt;</span><span class="syn-type">table</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"w-full text-denim-50"</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;</span><span class="syn-type">thead</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;</span><span class="syn-type">tr</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-left border-b border-denim-700"</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">th</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"pb-2"</span><span class="syn-op">&gt;</span><span class="syn-str">ID</span><span class="syn-op">&lt;/</span><span class="syn-type">th</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">th</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"pb-2"</span><span class="syn-op">&gt;</span><span class="syn-str">Customer</span><span class="syn-op">&lt;/</span><span class="syn-type">th</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">th</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"pb-2"</span><span class="syn-op">&gt;</span><span class="syn-str">Amount</span><span class="syn-op">&lt;/</span><span class="syn-type">th</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">th</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"pb-2"</span><span class="syn-op">&gt;</span><span class="syn-str">Status</span><span class="syn-op">&lt;/</span><span class="syn-type">th</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">th</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"pb-2"</span><span class="syn-op">&gt;</span><span class="syn-str">Actions</span><span class="syn-op">&lt;/</span><span class="syn-type">th</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;/</span><span class="syn-type">tr</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;/</span><span class="syn-type">thead</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;</span><span class="syn-type">tbody</span><span class="syn-op">&gt;</span>
          <span class="syn-punc">{(</span><span class="syn-var">invoices</span> <span class="syn-op">??</span> <span class="syn-punc">[]).</span><span class="syn-fn">map</span><span class="syn-punc">((</span><span class="syn-var">inv</span><span class="syn-punc">)</span> <span class="syn-op">=&gt;</span> <span class="syn-punc">(</span>
            <span class="syn-op">&lt;</span><span class="syn-type">tr</span> <span class="syn-attr">key</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-var">inv</span><span class="syn-punc">.</span><span class="syn-var">id</span><span class="syn-punc">}</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"border-b border-denim-800"</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">td</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"py-3"</span><span class="syn-op">&gt;</span><span class="syn-punc">{</span><span class="syn-var">inv</span><span class="syn-punc">.</span><span class="syn-var">id</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">td</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">td</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"py-3"</span><span class="syn-op">&gt;</span><span class="syn-punc">{</span><span class="syn-var">inv</span><span class="syn-punc">.</span><span class="syn-var">customer_name</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">td</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">td</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"py-3"</span><span class="syn-op">&gt;</span><span class="syn-str">$</span><span class="syn-punc">{</span><span class="syn-var">inv</span><span class="syn-punc">.</span><span class="syn-var">amount</span><span class="syn-punc">.</span><span class="syn-fn">toFixed</span><span class="syn-punc">(</span><span class="syn-num">2</span><span class="syn-punc">)</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">td</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">td</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"py-3"</span><span class="syn-op">&gt;</span>
                <span class="syn-op">&lt;</span><span class="syn-type">span</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-var">inv</span><span class="syn-punc">.</span><span class="syn-var">status</span> <span class="syn-op">===</span> <span class="syn-str">"paid"</span> <span class="syn-op">?</span> <span class="syn-str">"text-green-400"</span> <span class="syn-op">:</span> <span class="syn-str">"text-wash-400"</span><span class="syn-punc">}</span><span class="syn-op">&gt;</span>
                  <span class="syn-punc">{</span><span class="syn-var">inv</span><span class="syn-punc">.</span><span class="syn-var">status</span><span class="syn-punc">}</span>
                <span class="syn-op">&lt;/</span><span class="syn-type">span</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;/</span><span class="syn-type">td</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">td</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"py-3"</span><span class="syn-op">&gt;</span>
                <span class="syn-op">&lt;</span><span class="syn-type">button</span> <span class="syn-attr">onClick</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">setViewInvoice</span><span class="syn-punc">(</span><span class="syn-var">inv</span><span class="syn-punc">)</span><span class="syn-punc">}</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-wash-400 hover:text-wash-300"</span><span class="syn-op">&gt;</span>View<span class="syn-op">&lt;/</span><span class="syn-type">button</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;/</span><span class="syn-type">td</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;/</span><span class="syn-type">tr</span><span class="syn-op">&gt;</span>
          <span class="syn-punc">))}</span>
        <span class="syn-op">&lt;/</span><span class="syn-type">tbody</span><span class="syn-op">&gt;</span>
      <span class="syn-op">&lt;/</span><span class="syn-type">table</span><span class="syn-op">&gt;</span>

      <span class="syn-punc">{</span><span class="syn-var">viewInvoice</span> <span class="syn-op">&amp;&amp;</span> <span class="syn-punc">(</span>
        <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"fixed inset-0 bg-black/50 flex items-center justify-center"</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"bg-denim-800 p-6 rounded-lg w-[28rem]"</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"flex justify-between items-start mb-4"</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">h2</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-xl font-bold text-denim-50"</span><span class="syn-op">&gt;</span><span class="syn-str">Invoice #</span><span class="syn-punc">{</span><span class="syn-var">viewInvoice</span><span class="syn-punc">.</span><span class="syn-var">id</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">h2</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">button</span> <span class="syn-attr">onClick</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-fn">setViewInvoice</span><span class="syn-punc">(</span><span class="syn-kw">null</span><span class="syn-punc">)</span><span class="syn-punc">}</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-denim-400 hover:text-denim-200"</span><span class="syn-op">&gt;</span>x<span class="syn-op">&lt;/</span><span class="syn-type">button</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"space-y-3 mb-6"</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"flex justify-between"</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;</span><span class="syn-type">span</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-denim-400"</span><span class="syn-op">&gt;</span><span class="syn-str">Customer</span><span class="syn-op">&lt;/</span><span class="syn-type">span</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;</span><span class="syn-type">span</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-denim-50"</span><span class="syn-op">&gt;</span><span class="syn-punc">{</span><span class="syn-var">viewInvoice</span><span class="syn-punc">.</span><span class="syn-var">customer_name</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">span</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"flex justify-between"</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;</span><span class="syn-type">span</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-denim-400"</span><span class="syn-op">&gt;</span><span class="syn-str">Amount</span><span class="syn-op">&lt;/</span><span class="syn-type">span</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;</span><span class="syn-type">span</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-denim-50 font-bold"</span><span class="syn-op">&gt;</span><span class="syn-str">$</span><span class="syn-punc">{</span><span class="syn-var">viewInvoice</span><span class="syn-punc">.</span><span class="syn-var">amount</span><span class="syn-punc">.</span><span class="syn-fn">toFixed</span><span class="syn-punc">(</span><span class="syn-num">2</span><span class="syn-punc">)</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">span</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"flex justify-between"</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;</span><span class="syn-type">span</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-denim-400"</span><span class="syn-op">&gt;</span><span class="syn-str">Status</span><span class="syn-op">&lt;/</span><span class="syn-type">span</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;</span><span class="syn-type">span</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-var">viewInvoice</span><span class="syn-punc">.</span><span class="syn-var">status</span> <span class="syn-op">===</span> <span class="syn-str">"paid"</span> <span class="syn-op">?</span> <span class="syn-str">"text-green-400"</span> <span class="syn-op">:</span> <span class="syn-str">"text-wash-400"</span><span class="syn-punc">}</span><span class="syn-op">&gt;</span><span class="syn-punc">{</span><span class="syn-var">viewInvoice</span><span class="syn-punc">.</span><span class="syn-var">status</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">span</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"flex justify-between"</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;</span><span class="syn-type">span</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-denim-400"</span><span class="syn-op">&gt;</span><span class="syn-str">Due Date</span><span class="syn-op">&lt;/</span><span class="syn-type">span</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;</span><span class="syn-type">span</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-denim-50"</span><span class="syn-op">&gt;</span><span class="syn-punc">{</span><span class="syn-var">viewInvoice</span><span class="syn-punc">.</span><span class="syn-var">due_date</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">span</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
              <span class="syn-op">&lt;</span><span class="syn-type">div</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"border-t border-denim-700 pt-3 mt-3"</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;</span><span class="syn-type">span</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-denim-400 block mb-1"</span><span class="syn-op">&gt;</span><span class="syn-str">Description</span><span class="syn-op">&lt;/</span><span class="syn-type">span</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;</span><span class="syn-type">p</span> <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"text-denim-200"</span><span class="syn-op">&gt;</span><span class="syn-punc">{</span><span class="syn-var">viewInvoice</span><span class="syn-punc">.</span><span class="syn-var">description</span><span class="syn-punc">}</span><span class="syn-op">&lt;/</span><span class="syn-type">p</span><span class="syn-op">&gt;</span><span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
            <span class="syn-op">&lt;</span><span class="syn-type">button</span>
              <span class="syn-attr">onClick</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-punc">()</span> <span class="syn-op">=&gt;</span> <span class="syn-var">statusMutation</span><span class="syn-punc">.</span><span class="syn-fn">mutate</span><span class="syn-punc">()</span><span class="syn-punc">}</span>
              <span class="syn-attr">disabled</span><span class="syn-op">=</span><span class="syn-punc">{</span><span class="syn-var">viewInvoice</span><span class="syn-punc">.</span><span class="syn-var">status</span> <span class="syn-op">===</span> <span class="syn-str">"paid"</span> <span class="syn-op">||</span> <span class="syn-var">statusMutation</span><span class="syn-punc">.</span><span class="syn-var">isPending</span><span class="syn-punc">}</span>
              <span class="syn-attr">className</span><span class="syn-op">=</span><span class="syn-str">"w-full px-4 py-2 bg-green-600 text-white rounded hover:bg-green-500 disabled:opacity-50"</span>
            <span class="syn-op">&gt;</span>
              <span class="syn-punc">{</span><span class="syn-var">statusMutation</span><span class="syn-punc">.</span><span class="syn-var">isPending</span> <span class="syn-op">?</span> <span class="syn-str">"Marking..."</span> <span class="syn-op">:</span> <span class="syn-str">"Mark as Paid"</span><span class="syn-punc">}</span>
            <span class="syn-op">&lt;/</span><span class="syn-type">button</span><span class="syn-op">&gt;</span>
          <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
        <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
      <span class="syn-punc">)}</span>
    <span class="syn-op">&lt;/</span><span class="syn-type">div</span><span class="syn-op">&gt;</span>
  <span class="syn-punc">)</span><span class="syn-punc">;</span>
<span class="syn-punc">}</span></code></pre>`;

export function DashboardCode() {
  return <div dangerouslySetInnerHTML={{ __html: dashboardCode }} />;
}

export function CustomersCode() {
  return <div dangerouslySetInnerHTML={{ __html: customersCode }} />;
}

export function InvoicesCode() {
  return <div dangerouslySetInnerHTML={{ __html: invoicesCode }} />;
}
